### ISSUE TITLE
python2.7, centos 7?

### ISSUE THREAD

**Issue by mpictor** [myllynen/pcp-bcc-pmda#2]
`git log --pretty=oneline -n1`
> 7c12d81dbca3b0e120442a664d7188d914e317bd Cosmetics etc in preparation for a possible upstream merge

$ `./Install`
```
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: Enabled modules:
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: [u'biolatency', u'sysfork', u'tcplife']
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: Configuring modules:
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: biolatency
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: sysfork
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: tcplife
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: Modules configured.
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: Initializing modules:
[Sat Jan 20 01:35:47] pmdabcc(2352) Info: biolatency
Traceback (most recent call last):
  File "/var/lib/pcp/pmdas/bcc/pmdabcc.python", line 223, in <module>
    BCCPMDA('bcc', 499).run()
  File "/var/lib/pcp/pmdas/bcc/pmdabcc.python", line 59, in __init__
    self.init_modules()
  File "/var/lib/pcp/pmdas/bcc/pmdabcc.python", line 149, in init_modules
    except ModuleNotFoundError as error:
NameError: global name 'ModuleNotFoundError' is not defined

(above messages repeat 1x)

Install: cannot determine the Performance Metrics Domain from domain.h.python
```

This one can be fixed with
```diff
-    except ModuleNotFoundError as error:
+    except ImportError as error:
```

Then I get
$ `./Install`
```
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: Enabled modules:
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: [u'biolatency', u'sysfork', u'tcplife']
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: Configuring modules:
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: biolatency
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: sysfork
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: tcplife
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: Modules configured.
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: Initializing modules:
[Sat Jan 20 01:39:08] pmdabcc(2431) Info: biolatency
[Sat Jan 20 01:39:08] pmdabcc(2431) Error: No module named modules.biolatency
[Sat Jan 20 01:39:08] pmdabcc(2431) Error: Module biolatency not found, aborting.

(above messages repeat 1x)

Install: cannot determine the Performance Metrics Domain from domain.h.python
```

Editing `modules =` in bcc.conf, I get similar errors for whatever module is first - biotop, sysfork, tcplife.

bcc is v 0.6.0; as far as I can tell, all its tools work fine.
kernel is 4.9.75 and has the necessary options for bcc enabled
pcp is 3.11.x (IIRC)

What steps can I take to track down the source of the problem?

**Comment by myllynen** [comment]
Thanks for the report and sorry for the delay in response.

I've pushed a few fixes which should help here, at least all works ok now on Fedora 27 with BCC upstream packages (which provide Python 2 modules in python-bcc) from https://repo.iovisor.org/yum/nightly/f27/x86_64/. Could you please try out let me know how it goes? (Make sure you have `PCP_PYTHON_PROG=python2` set in _/etc/pcp.conf_ when using Python 2.)

Thanks.

**Comment by myllynen** [comment]
I presume this is working ok now, so closing. Thanks.
